"""API core subpackage for omanage."""

# Exports are available through submodule imports:
#   from .errors import ...
#   from .file_utils import ...
#   from .locking import ...
#   from .subprocess_utils import ...